version: '3.8'

services:
  manager:
    build:
      context: services/domainManager
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    env_file:
      - .env
    command: npm run start

  scanner:
    build:
      context: services/domainScanner
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - .env
    command: npm run start

  mongodb:
    image: mongo
    command: --quiet
    volumes:
      - mongodb-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_LOG_LEVEL: emergency
    ports:
      - '5672:5672' # default RabbitMQ port for AMQP
      - '15672:15672' # RabbitMQ Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongodb-data:
  rabbitmq-data:
