version: '3.8'

services:
  manager:
    build:
      context: services/domainManager
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    env_file:
      - .env
    command: npm run start

  scanner:
    build:
      context: services/domainScanner
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env
    command: npm run start

  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
